import { FPO } from '@/types';

export const fpoData: FPO[] = [
  // Maharashtra
  {
    id: 'mh-1',
    name: 'Nashik Farmers Producer Co. Ltd',
    state: 'Maharashtra',
    district: 'Nashik',
    location: 'Pimpalgaon Baswant, Nashik',
    lat: 20.1658,
    lng: 73.9875,
    contact: '+91 91234 56780',
    email: 'nashikfpo@agrimail.in',
    yearEstablished: 2014,
    services: ['Seed Supply', 'Cold Storage', 'Export Linkage'],
    rating: 4.8,
    description: 'Specializing in grape and onion export value chains. We empower over 2500 small-scale grape growers in the Nashik region.',
    tags: ['Export Specialist', 'Top Rated']
  },
  {
    id: 'mh-2',
    name: 'Sahyadri Farmers Producer Company',
    state: 'Maharashtra',
    district: 'Nashik',
    location: 'Mohadi, Nashik',
    lat: 20.1012,
    lng: 74.0154,
    contact: '+91 91234 56781',
    email: 'info@sahyadrifarms.com',
    yearEstablished: 2011,
    services: ['Retail Outlets', 'Food Processing', 'Agronomy Support'],
    rating: 4.9,
    description: 'A world-class processing facility representing the collective strength of Sahyadri valley farmers.',
    tags: ['Global Leader', 'Top Rated']
  },
  {
    id: 'mh-3',
    name: 'Pune Organic Growers FPO',
    state: 'Maharashtra',
    district: 'Pune',
    location: 'Khadki, Pune',
    lat: 18.5204,
    lng: 73.8567,
    contact: '+91 91234 56782',
    email: 'puneorganic@fpo.org',
    yearEstablished: 2016,
    services: ['Organic Certification', 'Direct Marketing', 'Compost Supply'],
    rating: 4.6,
    description: 'Providing premium organic produce directly from farm to urban plates in the Pune metropolitan area.',
    tags: ['Organic', 'Eco-friendly']
  },
  // Punjab
  {
    id: 'pb-1',
    name: 'Ludhiana Golden Grain FPO',
    state: 'Punjab',
    district: 'Ludhiana',
    location: 'Khanna, Ludhiana',
    lat: 30.7071,
    lng: 76.2160,
    contact: '+91 91234 56783',
    email: 'ludhianagrain@punjabagri.com',
    yearEstablished: 2015,
    services: ['Machinery Bank', 'Quality Seeds', 'Warehousing'],
    rating: 4.5,
    description: 'Operating in Asia\'s largest grain market (Khanna), we ensure fair wheat and paddy transactions for members.',
    tags: ['Large Scale', 'Grain Tech']
  },
  {
    id: 'pb-2',
    name: 'Amritsar Orchardists Co.',
    state: 'Punjab',
    district: 'Amritsar',
    location: 'Ajnala, Amritsar',
    lat: 31.8415,
    lng: 74.7611,
    contact: '+91 91234 56784',
    email: 'amritsarorchards@fpo.in',
    yearEstablished: 2017,
    services: ['Horticulture Training', 'Fruit Processing', 'Mandi Linkage'],
    rating: 4.4,
    description: 'Transforming citrus and guava farming in the border belt through modern cultivation techniques.',
    tags: ['Horticulture']
  },
  // Uttar Pradesh
  {
    id: 'up-1',
    name: 'UP Potato Vikas FPO',
    state: 'Uttar Pradesh',
    district: 'Agra',
    location: 'Fatehabad, Agra',
    lat: 27.1767,
    lng: 78.1081,
    contact: '+91 91234 56785',
    email: 'up-potato-fpo@agra.gov.in',
    yearEstablished: 2013,
    services: ['Potato Seed Distribution', 'Cold Chain', 'Processing Linkage'],
    rating: 4.3,
    description: 'Bridging the gap between potato farmers and major snacks manufacturing companies.',
    tags: ['Value Chain']
  },
  {
    id: 'up-2',
    name: 'Varanasi Vegetable Hub',
    state: 'Uttar Pradesh',
    district: 'Varanasi',
    location: 'Rajatalab, Varanasi',
    lat: 25.3176,
    lng: 82.9739,
    contact: '+91 91234 56786',
    email: 'varanasiveg@fpo.org.in',
    yearEstablished: 2018,
    services: ['Vegetable Aggregation', 'Transportation', 'Training Center'],
    rating: 4.7,
    description: 'Leveraging the Varanasi air cargo terminal to export fresh green vegetables to Gulf countries.',
    tags: ['Export Ready', 'Fresh Produce']
  },
  // Telangana
  {
    id: 'tg-1',
    name: 'Telangana Agri Hub FPO',
    state: 'Telangana',
    district: 'Hyderabad',
    location: 'Gachibowli, Hyderabad',
    lat: 17.4448,
    lng: 78.3498,
    contact: '+91 91234 56787',
    email: 'agrihub@telangana.gov.in',
    yearEstablished: 2019,
    services: ['Tech Advisory', 'Precision Farming', 'Seed Bank'],
    rating: 4.7,
    description: 'Focusing on integrating IoT and drone technology into daily farming operations.',
    tags: ['Modern Agriculture', 'Tech-First']
  },
  {
    id: 'tg-2',
    name: 'Warangal Red Chilli Growers',
    state: 'Telangana',
    district: 'Warangal',
    location: 'Enumamula, Warangal',
    lat: 17.9689,
    lng: 79.5941,
    contact: '+91 91234 56788',
    email: 'warangalchilli@fpo.com',
    yearEstablished: 2012,
    services: ['Chilli Drying Facilities', 'Cold Storage', 'Bulk Sales'],
    rating: 4.5,
    description: 'Managing one of the largest chilli procurement centers in South India.',
    tags: ['Spices Special']
  },
  // Andhra Pradesh
  {
    id: 'ap-1',
    name: 'Guntur Chilli Export FPO',
    state: 'Andhra Pradesh',
    district: 'Guntur',
    location: 'Mirchi Yard, Guntur',
    lat: 16.3067,
    lng: 80.4365,
    contact: '+91 91234 56789',
    email: 'gunturchilli@apfpo.in',
    yearEstablished: 2014,
    services: ['Export Sorting', 'Lab Testing', 'Global Logistics'],
    rating: 4.8,
    description: 'World-renowned for Guntur chillies, providing direct export channels to farmers.',
    tags: ['Export Giant']
  },
  {
    id: 'ap-2',
    name: 'Krishna Delta Paddy FPO',
    state: 'Andhra Pradesh',
    district: 'Vijayawada',
    location: 'Benz Circle, Vijayawada',
    lat: 16.5062,
    lng: 80.6480,
    contact: '+91 91234 56790',
    email: 'krishnapaddy@fpo.org',
    yearEstablished: 2015,
    services: ['Seed Processing', 'Milling Support', 'Crop Insurance'],
    rating: 4.3,
    description: 'Securing the livelihoods of delta region farmers through collective paddy procurement.',
    tags: ['Delta Special']
  },
  // Karnataka
  {
    id: 'ka-1',
    name: 'Kodagu Coffee Growers FPO',
    state: 'Karnataka',
    district: 'Kodagu',
    location: 'Madikeri, Kodagu',
    lat: 12.4244,
    lng: 75.7381,
    contact: '+91 91234 56791',
    email: 'kodagucoffee@fpo.co.in',
    yearEstablished: 2010,
    services: ['Coffee Curing', 'Export Grading', 'Shade Management Training'],
    rating: 4.9,
    description: 'Preserving the heritage of Coorg coffee while ensuring international market prices for small growers.',
    tags: ['Coffee Heritage', 'Global Export']
  },
  {
    id: 'ka-2',
    name: 'Hubli Pulse Hub FPO',
    state: 'Karnataka',
    district: 'Dharwad',
    location: 'Hubli APMC, Dharwad',
    lat: 15.3647,
    lng: 75.1240,
    contact: '+91 91234 56792',
    email: 'hublipulses@agri.ka.gov.in',
    yearEstablished: 2016,
    services: ['Pulse Processing', 'Quality Packaging', 'Brand Marketing'],
    rating: 4.5,
    description: 'Adding value to pulses and lentils through cleaning, grading, and retail branding.',
    tags: ['Pulses Specialist']
  },
  // Tamil Nadu
  {
    id: 'tn-1',
    name: 'Nilgiri Tea Farmers FPO',
    state: 'Tamil Nadu',
    district: 'The Nilgiris',
    location: 'Coonoor, Nilgiris',
    lat: 11.3530,
    lng: 76.7959,
    contact: '+91 91234 56793',
    email: 'nilgiritea@tnfpo.gov.in',
    yearEstablished: 2011,
    services: ['Tea Processing', 'Fair Trade Certification', 'Direct Export'],
    rating: 4.7,
    description: 'Representing the small tea growers of the blue mountains with focus on specialty teas.',
    tags: ['Hill Agriculture']
  },
  {
    id: 'tn-2',
    name: 'Madurai Jasmine Connect',
    state: 'Tamil Nadu',
    district: 'Madurai',
    location: 'Mattuthavani, Madurai',
    lat: 9.9252,
    lng: 78.1198,
    contact: '+91 91234 56794',
    email: 'maduraijasmine@fpo.in',
    yearEstablished: 2017,
    services: ['Flower Extraction', 'Cold Transport', 'Perfume Industry Linkage'],
    rating: 4.6,
    description: 'Ensuring the world-famous Madurai Malli reaches global markets within 24 hours of plucking.',
    tags: ['Horticulture Specialists']
  },
  // Gujarat
  {
    id: 'gj-1',
    name: 'Kutch Date Palm FPO',
    state: 'Gujarat',
    district: 'Kutch',
    location: 'Bhuj, Kutch',
    lat: 23.2381,
    lng: 69.6669,
    contact: '+91 91234 56795',
    email: 'kutchdates@gjagri.com',
    yearEstablished: 2013,
    services: ['Tissue Culture Seeds', 'Drying Units', 'Export Packing'],
    rating: 4.5,
    description: 'Pioneering the transformation of Kutch into a hub for premium date varieties.',
    tags: ['Arid Lands Specialist']
  },
  {
    id: 'gj-2',
    name: 'Anand Dairy Farmers FPO',
    state: 'Gujarat',
    district: 'Anand',
    location: 'Amul Hub, Anand',
    lat: 22.5645,
    lng: 72.9289,
    contact: '+91 91234 56796',
    email: 'ananddairy@fpo.org',
    yearEstablished: 1946, // Historical reference
    services: ['Cattle Feed Supply', 'Veterinary Services', 'Chilling Centers'],
    rating: 5.0,
    description: 'The root of the White Revolution, continuing to empower millions of dairy farmers.',
    tags: ['Dairy Giant', 'Historical']
  },
  // Rajasthan
  {
    id: 'rj-1',
    name: 'Jodhpur Spices FPO',
    state: 'Rajasthan',
    district: 'Jodhpur',
    location: 'Mandore, Jodhpur',
    lat: 26.2389,
    lng: 73.0243,
    contact: '+91 91234 56797',
    email: 'jodhpurspices@rj.gov.in',
    yearEstablished: 2014,
    services: ['Cumin Processing', 'Lab Testing', 'Commodity Trading'],
    rating: 4.4,
    description: 'Promoting organic spice cultivation in the arid regions of Marwar.',
    tags: ['Spices Hub']
  },
  // Bihar
  {
    id: 'br-1',
    name: 'Muzaffarpur Litchi Growers',
    state: 'Bihar',
    district: 'Muzaffarpur',
    location: 'Mushahari, Muzaffarpur',
    lat: 26.1209,
    lng: 85.3647,
    contact: '+91 91234 56798',
    email: 'muzaffarpurlitchi@fpo.in',
    yearEstablished: 2012,
    services: ['Post-harvest Handling', 'Cold Storage Access', 'Direct Export Channels'],
    rating: 4.6,
    description: 'Protecting the GI tagged Shahi Litchi farmers through collective marketing and logistics.',
    tags: ['GI Tagged Specialist']
  },
  // West Bengal
  {
    id: 'wb-1',
    name: 'Darjeeling Tea Farmers Co.',
    state: 'West Bengal',
    district: 'Darjeeling',
    location: 'Kurseong, Darjeeling',
    lat: 26.8812,
    lng: 88.2778,
    contact: '+91 91234 56799',
    email: 'darjeelingtea@wb.gov.in',
    yearEstablished: 2008,
    services: ['Organic Tea Curing', 'Export Certification', 'Tourism Linkage'],
    rating: 4.8,
    description: 'Safeguarding the heritage of Darjeeling tea while improving margins for small growers.',
    tags: ['Premium Export']
  },
  // Madhya Pradesh
  {
    id: 'mp-1',
    name: 'Indore Soy Connect FPO',
    state: 'Madhya Pradesh',
    district: 'Indore',
    location: 'Pithampur Road, Indore',
    lat: 22.7196,
    lng: 75.8577,
    contact: '+91 91234 56800',
    email: 'indoresoy@fpo.mp.gov.in',
    yearEstablished: 2015,
    services: ['Soybean Seeds', 'Oil Extraction Linkage', 'Warehousing'],
    rating: 4.4,
    description: 'Deeply integrated into the heart of India\'s soybean production belt.',
    tags: ['Oilseeds Specialist']
  },
  // Odisha
  {
    id: 'or-1',
    name: 'Koraput Coffee FPO',
    state: 'Odisha',
    district: 'Koraput',
    location: 'Similiguda, Koraput',
    lat: 18.8105,
    lng: 82.7126,
    contact: '+91 91234 56801',
    email: 'koraputcoffee@odisha.gov.in',
    yearEstablished: 2018,
    services: ['Tribal Farmer Support', 'Coffee Processing', 'State Marketing'],
    rating: 4.6,
    description: 'Empowering tribal communities through sustainable forest-grown coffee production.',
    tags: ['Tribal Empowerment', 'Sustainable']
  },
  // Kerala
  {
    id: 'kl-1',
    name: 'Wayanad Spice Valley',
    state: 'Kerala',
    district: 'Wayanad',
    location: 'Kalpetta, Wayanad',
    lat: 11.6050,
    lng: 76.0827,
    contact: '+91 91234 56802',
    email: 'wayanadspices@fpo.kl.gov.in',
    yearEstablished: 2013,
    services: ['Pepper Grinding Units', 'Cardamom Drying', 'Organic Certification'],
    rating: 4.8,
    description: 'Promoting high-value spice exports from the Western Ghats of Kerala.',
    tags: ['Spices Special', 'Western Ghats']
  },
  // Assam
  {
    id: 'as-1',
    name: 'Assam Orthodox Tea FPO',
    state: 'Assam',
    district: 'Dibrugarh',
    location: 'Tinsukia Road, Dibrugarh',
    lat: 27.4728,
    lng: 94.9120,
    contact: '+91 91234 56803',
    email: 'assamtea-fpo@as.gov.in',
    yearEstablished: 2016,
    services: ['Processing Factories', 'Quality Control', 'Auction Support'],
    rating: 4.7,
    description: 'Ensuring small tea growers get fair participation in the Guwahati tea auctions.',
    tags: ['Tea Industry']
  },
  // Himachal Pradesh
  {
    id: 'hp-1',
    name: 'Shimla Apple Growers FPO',
    state: 'Himachal Pradesh',
    district: 'Shimla',
    location: 'Rohru, Shimla',
    lat: 31.2111,
    lng: 77.7525,
    contact: '+91 91234 56804',
    email: 'shimlaapple@hp.gov.in',
    yearEstablished: 2011,
    services: ['CA Storage', 'Grading & Waxing', 'Carton Supply'],
    rating: 4.9,
    description: 'Protecting the interest of high-altitude apple farmers with temperature-controlled logistics.',
    tags: ['Apple Special', 'Cold Chain']
  },
  // Uttarakhand
  {
    id: 'ut-1',
    name: 'Himalayan Millet Hub',
    state: 'Uttarakhand',
    district: 'Dehradun',
    location: 'Vikhasnagar, Dehradun',
    lat: 30.3165,
    lng: 78.0322,
    contact: '+91 91234 56805',
    email: 'himalayanmillet@ut.gov.in',
    yearEstablished: 2020,
    services: ['Millet Processing', 'Regional Branding', 'Technical Guidance'],
    rating: 4.5,
    description: 'Reviving traditional Himalayan millets through modern processing and global marketing.',
    tags: ['Superfoods', 'Mountain Agri']
  },
  // Chhattisgarh
  {
    id: 'ct-1',
    name: 'Bastar Tribal Produce FPO',
    state: 'Chhattisgarh',
    district: 'Bastar',
    location: 'Jagdalpur, Bastar',
    lat: 19.0736,
    lng: 82.0294,
    contact: '+91 91234 56806',
    email: 'bastarfpo@cg.gov.in',
    yearEstablished: 2019,
    services: ['Minor Forest Produce Aggregation', 'Imli Processing', 'Fair Trade Sale'],
    rating: 4.3,
    description: 'Supporting tribal farmers in collecting and processing non-timber forest produce sustainably.',
    tags: ['Tribal Produce', 'Eco-Social']
  },
  // Jharkhand
  {
    id: 'jh-1',
    name: 'Ranchi Vegetable Export FPO',
    state: 'Jharkhand',
    district: 'Ranchi',
    location: 'Namkum, Ranchi',
    lat: 23.3441,
    lng: 85.3096,
    contact: '+91 91234 56807',
    email: 'ranchiveg@jh.gov.in',
    yearEstablished: 2017,
    services: ['Greenhouse Supplies', 'Daily Aggregation', 'Inter-state Transport'],
    rating: 4.4,
    description: 'Leveraging Jharkhand\'s favorable climate for high-quality off-season vegetable production.',
    tags: ['Fresh Aggregators']
  },
  // Haryana
  {
    id: 'hr-1',
    name: 'Karnal Basmati Growers',
    state: 'Haryana',
    district: 'Karnal',
    location: 'Seed Farm Road, Karnal',
    lat: 29.6857,
    lng: 76.9907,
    contact: '+91 91234 56808',
    email: 'karnalbasmati@hr.gov.in',
    yearEstablished: 2014,
    services: ['Purity Testing', 'Basmati Milling', 'Export Linkage'],
    rating: 4.7,
    description: 'Ensuring the quality and brand value of legendary Karnal Basmati in international markets.',
    tags: ['Basmati Special']
  },
  // North East - Sikkim
  {
    id: 'sk-1',
    name: 'Sikkim Organic Mission FPO',
    state: 'Sikkim',
    district: 'Gangtok',
    location: 'Middle Camp, Gangtok',
    lat: 27.3314,
    lng: 88.6138,
    contact: '+91 91234 56809',
    email: 'sikkimorganic@fpo.in',
    yearEstablished: 2010,
    services: ['Organic Inputs', 'Certification Support', 'Market Linkage'],
    rating: 4.9,
    description: 'Supporting the first fully organic state of India with premium organic certification and international exports.',
    tags: ['100% Organic', 'Pioneers']
  },
  // Central - Chhattisgarh (Additional)
  {
    id: 'ct-2',
    name: 'Raipur Rice Cluster FPO',
    state: 'Chhattisgarh',
    district: 'Raipur',
    location: 'Telibandha, Raipur',
    lat: 21.2514,
    lng: 81.6296,
    contact: '+91 91234 56810',
    email: 'raipurrice@cg.gov.in',
    yearEstablished: 2016,
    services: ['Rice Milling', 'Seed Prodcution', 'Warehouse Facilities'],
    rating: 4.4,
    description: 'Focusing on high-yield paddy varieties and centralized processing for the rice bowl of India.',
    tags: ['Rice Bowl']
  }
];
